product_category:
    path: /product/add
    defaults: { _controller: AppBundle:Default:createProduct }
show_product:
    path: /product/show
    defaults: { _controller: AppBundle:Default:show }
show_All:
    path: /product/showAllProducts
    defaults: { _controller: AppBundle:Default:showAll }
add_group:
    path: /user/insert
    defaults: { _controller: AppBundle:userGroup:addGroup }
insert_group:
    path: /user/add
    defaults: { _controller: AppBundle:userGroup:addUserGroup }
user_showgroup:
    path: /user/showGroup
    defaults: { _controller: AppBundle:userGroup:showGroup }