email_box_homepage:
    path:     /
    defaults: { _controller: EmailBoxBundle:Email:inbox }
email_compose:
    path:     /emails/compose
    defaults: { _controller: EmailBoxBundle:Email:compose }
email_send_mail:
    path:     /emails/send-mail
    defaults: { _controller: EmailBoxBundle:Email:send }
email_sent:
    path:     /emails/sent
    defaults: { _controller: EmailBoxBundle:Default:sent }    
email_draft:
    path:     /emails/draft
    defaults: { _controller: EmailBoxBundle:Default:draft }
email_details:
    path:     /emails/details/{emailId}
    defaults: { _controller: EmailBoxBundle:Default:view, emailId:null }
email_reply:
    path:     /emails/reply/{emailId}
    defaults: { _controller: EmailBoxBundle:Email:reply , emailId:null }
email_forward:
    path:     /emails/forward/{emailId}
    defaults: { _controller: EmailBoxBundle:Email:forward }
email_delete:
    path:     /emails/delete/{emailId}
    defaults: { _controller: EmailBoxBundle:Email:delete }
admin:
    path: /admin
    defaults: {_controller: EmailBoxBundle:Base:admin}
