email_test:
    path: /emails/{id}/{text}
    defaults: { _controller: EmailBoxBundle:Default:demo, id: null ,text: null }
    requirements: 
         id: "\d+" 
         text: "[a-z]+"

ref_bundle:
    path: /name
    defaults: { _controller: EmailBoxBundle:Email:reference }

demo:
    path: /test
    defaults: { _controller: AppBundle:Default:index }    
                
test_include:
    path: /test-include
    defaults: { _controller: EmailBoxBundle:Test:include }

test_extends:
    path: /test-extends
    defaults: { _controller: EmailBoxBundle:Test:extends }